#!/bin/bash
USB3_IRQ=`cat /proc/interrupts | grep "xhci-hcd:usb3" | awk -F : '{print $1}'`
USB5_IRQ=`cat /proc/interrupts | grep "xhci-hcd:usb5" | awk -F : '{print $1}'`
echo 5 > /proc/irq/${USB3_IRQ}/smp_affinity_list
echo 6 > /proc/irq/${USB5_IRQ}/smp_affinity_list

if [ -f /sys/class/net/eth0/queues/rx-0/rps_cpus ]; then
	echo f > /sys/class/net/eth0/queues/rx-0/rps_cpus
fi

# fix chromium if possible
if [ -e "/usr/lib/chromium-browser/libEGL.so" -a -e "/usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so" ]; then
	mv /usr/lib/chromium-browser/libEGL.so /usr/lib/chromium-browser/libEGL.so.org
	ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/chromium-browser/libEGL.so
fi
if [ -e "/usr/lib/chromium-browser/libGLESv2.so" -a -e "/usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so" ]; then
	mv /usr/lib/chromium-browser/libGLESv2.so /usr/lib/chromium-browser/libGLESv2.so.org
	ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/chromium-browser/libGLESv2.so
fi

# attempt to fix mali every reboot in case mesa overwrites it
rm -fr /etc/ld.so.conf.d/arm-linux-gnueabihf_EGL.conf
rm -fr /usr/lib/arm-linux-gnueabihf/mali-egl/ld.so.conf

rm -fr /usr/lib/arm-linux-gnueabihf/libEGL*
rm -fr /usr/lib/arm-linux-gnueabihf/libGLESv2*
rm -fr /usr/lib/arm-linux-gnueabihf/libGLESv1*

# Links
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libEGL.so
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libGLESv1_CM.so
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2
ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1
